apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: airflow
  name: airflow-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      octopusexport: OctopusExport
  strategy: 
    type: RollingUpdate
  template: 
    metadata: 
      labels: 
        app: airflow
        octopusexport: OctopusExport
    spec: 
      containers: 
        - 
          image: apache/airflow
          name: airflow
          ports: 
            ? "-containerPort": 80
